### ISSUE TITLE
Incorrect accumulation of wins/losses (55% win when should be 66%)

### ISSUE THREAD

**Issue by jwoLondon** [kamohoaliix/MontyHallProcessing#1]
The problem lies in `swapPos()`. Line 84 correctly identifies one of the doors that hasn't been revealed and isn't the contestant's choice. After this swap has taken place, the method should move on to `winOrLose`, but it currently just increases `counter` by one and tries to swap again if the conditions are matched. This means that if the method swaps when counter=0, it can swap a second time (i.e. back to the original choice) at either counter=1 or counter=2.

The solution is to insert `break;` after line 86 to guarantee just one swap:

```
void swapPos(){
  // Loop through doors array
  int counter = 0;
  while(counter < 3){
    // Check to see if the current door is neither the revealed door, nor the user's choice
    if(counter != choice && counter != reveal){
      // Switch to the other available door
      choice = counter;
      break;
    }
    // Move to next door for check
    counter++;
  }
  // Move to win or lose stage
  winOrLose();
}
```

This gives the expected long-term win probability of 66%.

**Comment by br34th3r** [comment]
I have no idea how on earth you managed to spot that, but thank you for your help professor!
